apiVersion: v1
kind: Namespace
metadata:
  name: etherbank-api-dev
---
apiVersion: v1
kind: Service
metadata:
  name: ether-cache-service
  namespace: etherbank-api-dev
spec:
  ports:
  - port: 6379
  selector:
    app: etherbank-cache
---
apiVersion: v1
kind: Service
metadata:
  name: etherbank-api-service
  namespace: etherbank-api-dev
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: etherbank-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherbank-api-deployment
  namespace: etherbank-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherbank-api
  template:
    metadata:
      labels:
        app: etherbank-api
    spec:
      containers:
      - env:
        - name: PORT
          value: 5000
        - name: APP_NAME
          value: EtherBank
        - name: REDIS_PORT
          value: 6379
        - name: REDIS_HOST
          value: ether-cache-service
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwtsecret
              name: ether-stage-secrets
        - name: ATLAS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: atlas_db_name
              name: ether-stage-secrets
        - name: ATLAS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: atlas_password
              name: ether-stage-secrets
        image: seyio/etherbank-api:latest
        name: api-server
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherbank-cache-deployment
  namespace: etherbank-api-dev
spec:
  selector:
    matchLabels:
      app: etherbank-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etherbank-cache
    spec:
      containers:
      - image: redis
        name: etherbank-cache
        ports:
        - containerPort: 6379
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: etherbank-api-ingress
  namespace: etherbank-api-dev
spec:
  rules:
  - host: oneblock.ddns.net
    http:
      paths:
      - backend:
          serviceName: etherbank-api-service
          servicePort: 80
