apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherbank-api-deployment
  namespace: etherbank-api-dev
spec:
  template:
    spec:
      containers:    
        - name: api-server
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: serverport
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: ssl_validation_toggle
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: app_name 
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: redisport
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: redishost
            - name: INFURA_API_URL
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: infura_api_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ether-prod-secrets
                  key:  jwtsecret
            - name: ATLAS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ether-prod-secrets
                  key:  atlas_db_name
            - name: ATLAS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ether-prod-secrets
                  key:  atlas_password
            - name: CONTRACT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: block-chain-secrets
                  key:  contract_private_key
            - name: CONTRACT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: block-chain-secrets
                  key:  contract_address
            - name: INFURA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: block-chain-secrets
                  key:  infura_token