- op: replace
  path: /spec/rules/0/host
  value: apioneblock.ddns.net

- op: add
  path: /metadata/annotations
  value: 
    kubernetes.io/ingress.class: nginx
- op: add
  path: /spec
  value: 
    rules:
      - host: apioneblock.ddns.net
        http:
          paths:
          - backend:
              serviceName: etherbank-api-service
              servicePort: 80