apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-api-prod

  
images:
- name: seyio/etherbank-api
  newTag: a6cebd95
resources:
- ../base
- namespace_prod.yml

patchesStrategicMerge:
- config-patch-prod.yml

patchesJson6902:
- path: ingress_patch_prod.yml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: etherbank-api-ingress
    namespace: etherbank-api-prod
    version: v1beta1
