apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-api-prod

images:
- name: seyio/etherbank-api
  newTag: 78cf1fbe
  
replicas:
- count: 1
  name: etherbank-api-deployment
resources:
- ../base
- namespace_prod.yml

patchesStrategicMerge:
- config-patch-prod.yml

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: etherbank-api-ingress
      namespace: etherbank-api-prod
    path: ingress_patch_prod.yml