apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherbank-api-deployment
  namespace: etherbank-api-dev
spec:
  template:
    spec:
      containers:    
        - name: api-server
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: serverport
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: app_name 
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: redisport
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: etherbank-config
                  key: redishost
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ether-stage-secrets
                  key:  jwtsecret
            - name: ATLAS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ether-stage-secrets
                  key:  atlas_db_name
            - name: ATLAS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ether-stage-secrets
                  key:  atlas_password