apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherbank-api-deployment
  namespace: etherbank-api-dev
spec:
  template:
    spec:
      containers:    
        - name: api-server
          env:
            - name: PORT
              value: 5000
            - name: APP_NAME
              value: 'EtherBank'
            - name: REDIS_PORT
              value: 6379
            - name: REDIS_HOST
              value: ether-cache-service
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ether-stage-secrets
                  key:  jwtsecret
            - name: ATLAS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ether-stage-secrets
                  key:  atlas_db_name
            - name: ATLAS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ether-stage-secrets
                  key:  atlas_password