apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-api-dev

  
images:
- name: seyio/etherbank-api
  newTag: 5341f4bd
resources:
- ../base
- namespace.yml

patchesStrategicMerge:
- config-patch-stage.yml

patchesJson6902:
- path: ingress_patch.yml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: etherbank-api-ingress
    namespace: etherbank-api-dev
    version: v1beta1
