apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-api-dev

  
images:
- name: seyio/etherbank-api
  newTag: b1a4d014
resources:
- ../base

patchesStrategicMerge:
- config-patch-stage.yml
