apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-api-dev

images:
- name: seyio/etherbank-api
  newTag: latest
  
replicas:
- count: 1
  name: etherbank-api-deployment
resources:
- ../base

patches:
- config-patch-stage.yml