apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-api-dev

  
images:
- name: seyio/etherbank-api
  newTag: b1a4d014
resources:
- ../base

patchesStrategicMerge:
- config-patch-stage.yml

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: etherbank-api-ingress
      namespace: etherbank-api-dev
    path: ingress_patch.yml
